version: '3'

services:
  customers-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    image: customers-service:1.0.0-SNAPSHOT
    restart: always
    ports:
      - "8080:8080"  # Map the container's 8082 port to the host's 8080 port

#  shop-customers:
#    image: shop-customers:1.0.0-SNAPSHOT
#    restart: always
#    environment:
#      SHOP_ORDER_URL: "http://shop-orders:8080"
#
#  shop-gateway:
#    image: shop-gateway:1.0.0-SNAPSHOT
#    restart: always
#    environment:
#      SHOP_CUSTOMER_URL: "http://shop-customers:8080"
#      SHOP_ORDER_URL: "http://shop-orders:8080"
#      SHOP_GATEWAY_HOST: "shop-gateway:8080"
#
