version: '3'

services:
  customers-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"

  orders-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    restart: always
    environment:
      SHOP_ORDER_URL: "http://customers-service:8081"
    ports:
      - "8082:8080"

  shop-gateway:
    build:
      context: ./shop-gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      SHOP_CUSTOMER_URL: "http://customers-service:8081"
      SHOP_ORDER_URL: "http://orders-service:8082"
      SHOP_GATEWAY_HOST: "shop-gateway:8080"
    ports:
      - "8080:8080"

  shop-ng:
    build:
      context: ./angular
      dockerfile: Dockerfile
    restart: always
    environment:
      API_URL: http://shop-gateway:8080/api
    ports:
      - "8083:80"