### Get all customers

GET http://localhost:8080/api/customers

### create/update
PUT http://localhost:8080/api/customers/68f222d6-a76d-44c0-afec-474489e31bc4
Content-Type: application/json

{
  "pesel": "95011903212",
  "name": "Testowy 2",
  "surname": "Testariusz",
  "age": 12
}


### Get customer by Id , you should change id

GET http://localhost:8080/api/customers/68f222d6-a76d-44c0-afec-474489e31bc4

### delete customer

DELETE http://localhost:8080/api/customers/68f222d6-a76d-44c0-afec-474489e31bc4




### Get all orders

GET http://localhost:8080/api/orders

### create/update

PUT http://localhost:8080/api/orders/72310089-a874-47e1-b0f1-0a54f09121cf
Content-Type: application/json

{
  "productName": "krzeslo",
  "quantity": 11,
  "customer": "68f222d6-a76d-44c0-afec-474489e31bc4"
}

### Get order by Id , you should change id

GET http://localhost:8080/api/orders/72310089-a874-47e1-b0f1-0a54f09121cf


### Deleting

DELETE http://localhost:8080/api/orders/72310089-a874-47e1-b0f1-0a54f09121cf