### Get all customers

GET http://localhost:8080/api/customers

### Get customer by Id

GET http://localhost:8080/api/customers/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### create/update
PUT http://localhost:8080/api/customers/68f222d6-a76d-44c0-afec-474489e31ec4
Content-Type: application/json

{
  "pesel": "95011903212",
  "name": "Testowy 2",
  "surname": "Testariusz",
  "age": 12
}

### get deleted customer

GET http://localhost:8080/api/customers/68f222d6-a76d-44c0-afec-474489e31ec4

### delete customer

DELETE http://localhost:8080/api/customers/68f222d6-a76d-44c0-afec-474489e31ec4



// ordery ----------------------------


### Get all orders

GET http://localhost:8080/api/orders

### get order by Id
GET http://localhost:8080/api/orders/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

### create/update

PUT http://localhost:8080/api/orders/62310089-a874-47e1-b0f1-0a54f0912112
Content-Type: application/json

{
  "productName": "testowy produkt",
  "quantity": 11,
  "customer": "68f222d6-a76d-44c0-afec-474489e31ec4"
}

### get order by Id
GET http://localhost:8080/api/orders/62310089-a874-47e1-b0f1-0a54f0912112

### Deleting

DELETE http://localhost:8080/api/orders/62310089-a874-47e1-b0f1-0a54f0912112

### GET orders by customer

GET http://localhost:8080/api/customers/2d9b1e8c-67c5-4188-a911-5f064a63d8ef/orders

### test

PUT http://localhost:8080/api/orders/28222129-38bf-49aa-af69-6daae4942d00
