#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service-1
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/customers/{customerId}
#            - Path=/api/customers
#        - id: order-service-1
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/orders
#            - Path=/api/orders/**
#        - id: order-service-2
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/customers/{customerId}/orders
#            - Path=/api/customers/{customerId}/orders/**
#
#
#
#
#
